# Copyright (c) 2018 Thomas Heller
#               2018 Patrick Diehl
#
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

version: 2
jobs:
    build:
        docker:
            - image: docker:17.05.0-ce-git
        steps:
            - run:
                name: Delete hip docker image
                command: |
                    apk update && apk add curl curl-dev bash
                    curl -X DELETE -u "$DOCKER_USER:$DOCKER_PASS" https://index.docker.io/v2/"stellargroup/build_env"/blobs/sha256:d94fc0af500a98a302455e8408c56bdf1d542191bd41931b535e283c4fa54796
